// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OpenTicket.proto

package org.openticket;

/**
 * <pre>
 **
 * The AreaList message defines a list of fare areas for spatial validity.
 * A start stop ID can be determined to restrict the validity to a certain
 * traveling direction.
 * </pre>
 *
 * Protobuf type {@code OpenTicket.AreaList}
 */
public  final class AreaList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OpenTicket.AreaList)
    AreaListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AreaList.newBuilder() to construct.
  private AreaList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AreaList() {
    startStopId_ = 0;
    containingAreaIds_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AreaList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            startStopId_ = input.readUInt32();
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              containingAreaIds_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000002;
            }
            containingAreaIds_.add(input.readUInt32());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
              containingAreaIds_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              containingAreaIds_.add(input.readUInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        containingAreaIds_ = java.util.Collections.unmodifiableList(containingAreaIds_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return OpenTicket.internal_static_OpenTicket_AreaList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return OpenTicket.internal_static_OpenTicket_AreaList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AreaList.class, AreaList.Builder.class);
  }

  private int bitField0_;
  public static final int STARTSTOPID_FIELD_NUMBER = 1;
  private int startStopId_;
  /**
   * <pre>
   * start stop ID (can be left empty if not applicable)
   * </pre>
   *
   * <code>uint32 startStopId = 1;</code>
   */
  public int getStartStopId() {
    return startStopId_;
  }

  public static final int CONTAININGAREAIDS_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Integer> containingAreaIds_;
  /**
   * <pre>
   * reference to one or more fare areas in which the legitimation is valid
   * </pre>
   *
   * <code>repeated uint32 containingAreaIds = 2;</code>
   */
  public java.util.List<java.lang.Integer>
      getContainingAreaIdsList() {
    return containingAreaIds_;
  }
  /**
   * <pre>
   * reference to one or more fare areas in which the legitimation is valid
   * </pre>
   *
   * <code>repeated uint32 containingAreaIds = 2;</code>
   */
  public int getContainingAreaIdsCount() {
    return containingAreaIds_.size();
  }
  /**
   * <pre>
   * reference to one or more fare areas in which the legitimation is valid
   * </pre>
   *
   * <code>repeated uint32 containingAreaIds = 2;</code>
   */
  public int getContainingAreaIds(int index) {
    return containingAreaIds_.get(index);
  }
  private int containingAreaIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (startStopId_ != 0) {
      output.writeUInt32(1, startStopId_);
    }
    if (getContainingAreaIdsList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(containingAreaIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < containingAreaIds_.size(); i++) {
      output.writeUInt32NoTag(containingAreaIds_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startStopId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, startStopId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < containingAreaIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(containingAreaIds_.get(i));
      }
      size += dataSize;
      if (!getContainingAreaIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      containingAreaIdsMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AreaList)) {
      return super.equals(obj);
    }
    AreaList other = (AreaList) obj;

    boolean result = true;
    result = result && (getStartStopId()
        == other.getStartStopId());
    result = result && getContainingAreaIdsList()
        .equals(other.getContainingAreaIdsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STARTSTOPID_FIELD_NUMBER;
    hash = (53 * hash) + getStartStopId();
    if (getContainingAreaIdsCount() > 0) {
      hash = (37 * hash) + CONTAININGAREAIDS_FIELD_NUMBER;
      hash = (53 * hash) + getContainingAreaIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AreaList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AreaList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AreaList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AreaList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AreaList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AreaList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AreaList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AreaList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AreaList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AreaList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AreaList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AreaList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AreaList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * The AreaList message defines a list of fare areas for spatial validity.
   * A start stop ID can be determined to restrict the validity to a certain
   * traveling direction.
   * </pre>
   *
   * Protobuf type {@code OpenTicket.AreaList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OpenTicket.AreaList)
          AreaListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OpenTicket.internal_static_OpenTicket_AreaList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OpenTicket.internal_static_OpenTicket_AreaList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AreaList.class, AreaList.Builder.class);
    }

    // Construct using de.openticket.AreaList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      startStopId_ = 0;

      containingAreaIds_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return OpenTicket.internal_static_OpenTicket_AreaList_descriptor;
    }

    @java.lang.Override
    public AreaList getDefaultInstanceForType() {
      return AreaList.getDefaultInstance();
    }

    @java.lang.Override
    public AreaList build() {
      AreaList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public AreaList buildPartial() {
      AreaList result = new AreaList(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.startStopId_ = startStopId_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        containingAreaIds_ = java.util.Collections.unmodifiableList(containingAreaIds_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.containingAreaIds_ = containingAreaIds_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AreaList) {
        return mergeFrom((AreaList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AreaList other) {
      if (other == AreaList.getDefaultInstance()) return this;
      if (other.getStartStopId() != 0) {
        setStartStopId(other.getStartStopId());
      }
      if (!other.containingAreaIds_.isEmpty()) {
        if (containingAreaIds_.isEmpty()) {
          containingAreaIds_ = other.containingAreaIds_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureContainingAreaIdsIsMutable();
          containingAreaIds_.addAll(other.containingAreaIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AreaList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AreaList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int startStopId_ ;
    /**
     * <pre>
     * start stop ID (can be left empty if not applicable)
     * </pre>
     *
     * <code>uint32 startStopId = 1;</code>
     */
    public int getStartStopId() {
      return startStopId_;
    }
    /**
     * <pre>
     * start stop ID (can be left empty if not applicable)
     * </pre>
     *
     * <code>uint32 startStopId = 1;</code>
     */
    public Builder setStartStopId(int value) {
      
      startStopId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * start stop ID (can be left empty if not applicable)
     * </pre>
     *
     * <code>uint32 startStopId = 1;</code>
     */
    public Builder clearStartStopId() {
      
      startStopId_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> containingAreaIds_ = java.util.Collections.emptyList();
    private void ensureContainingAreaIdsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        containingAreaIds_ = new java.util.ArrayList<java.lang.Integer>(containingAreaIds_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * reference to one or more fare areas in which the legitimation is valid
     * </pre>
     *
     * <code>repeated uint32 containingAreaIds = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getContainingAreaIdsList() {
      return java.util.Collections.unmodifiableList(containingAreaIds_);
    }
    /**
     * <pre>
     * reference to one or more fare areas in which the legitimation is valid
     * </pre>
     *
     * <code>repeated uint32 containingAreaIds = 2;</code>
     */
    public int getContainingAreaIdsCount() {
      return containingAreaIds_.size();
    }
    /**
     * <pre>
     * reference to one or more fare areas in which the legitimation is valid
     * </pre>
     *
     * <code>repeated uint32 containingAreaIds = 2;</code>
     */
    public int getContainingAreaIds(int index) {
      return containingAreaIds_.get(index);
    }
    /**
     * <pre>
     * reference to one or more fare areas in which the legitimation is valid
     * </pre>
     *
     * <code>repeated uint32 containingAreaIds = 2;</code>
     */
    public Builder setContainingAreaIds(
        int index, int value) {
      ensureContainingAreaIdsIsMutable();
      containingAreaIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * reference to one or more fare areas in which the legitimation is valid
     * </pre>
     *
     * <code>repeated uint32 containingAreaIds = 2;</code>
     */
    public Builder addContainingAreaIds(int value) {
      ensureContainingAreaIdsIsMutable();
      containingAreaIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * reference to one or more fare areas in which the legitimation is valid
     * </pre>
     *
     * <code>repeated uint32 containingAreaIds = 2;</code>
     */
    public Builder addAllContainingAreaIds(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureContainingAreaIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, containingAreaIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * reference to one or more fare areas in which the legitimation is valid
     * </pre>
     *
     * <code>repeated uint32 containingAreaIds = 2;</code>
     */
    public Builder clearContainingAreaIds() {
      containingAreaIds_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:OpenTicket.AreaList)
  }

  // @@protoc_insertion_point(class_scope:OpenTicket.AreaList)
  private static final AreaList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AreaList();
  }

  public static AreaList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AreaList>
      PARSER = new com.google.protobuf.AbstractParser<AreaList>() {
    @java.lang.Override
    public AreaList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AreaList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AreaList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AreaList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public AreaList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

