// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OpenTicket.proto

package org.openticket;

public interface EnvelopeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OpenTicket.Envelope)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the envelope version for parsing the ticket data
   * </pre>
   *
   * <code>uint32 envelopeVersion = 1;</code>
   */
  int getEnvelopeVersion();

  /**
   * <pre>
   * the key name which is used for signing ALL legitimations
   * </pre>
   *
   * <code>string keyName = 2;</code>
   */
  java.lang.String getKeyName();
  /**
   * <pre>
   * the key name which is used for signing ALL legitimations
   * </pre>
   *
   * <code>string keyName = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyNameBytes();

  /**
   * <pre>
   * as many RSA encrypted legitimations as arbitrary binary data
   * </pre>
   *
   * <code>repeated bytes encryptedLegitimations = 3;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getEncryptedLegitimationsList();
  /**
   * <pre>
   * as many RSA encrypted legitimations as arbitrary binary data
   * </pre>
   *
   * <code>repeated bytes encryptedLegitimations = 3;</code>
   */
  int getEncryptedLegitimationsCount();
  /**
   * <pre>
   * as many RSA encrypted legitimations as arbitrary binary data
   * </pre>
   *
   * <code>repeated bytes encryptedLegitimations = 3;</code>
   */
  com.google.protobuf.ByteString getEncryptedLegitimations(int index);
}
