// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OpenTicket.proto

package org.openticket;

/**
 * <pre>
 **
 * The Legitimation message contains all required information about a legitimation
 * to use for a trip.
 * </pre>
 *
 * Protobuf type {@code OpenTicket.Legitimation}
 */
public  final class Legitimation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OpenTicket.Legitimation)
    LegitimationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Legitimation.newBuilder() to construct.
  private Legitimation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Legitimation() {
    legitimationId_ = 0;
    dateTimeOfOrder_ = 0;
    validFrom_ = 0;
    validUntil_ = 0;
    optionFlags_ = 0;
    price_ = 0;
    tax_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Legitimation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            legitimationId_ = input.readUInt32();
            break;
          }
          case 16: {

            dateTimeOfOrder_ = input.readUInt32();
            break;
          }
          case 24: {

            validFrom_ = input.readUInt32();
            break;
          }
          case 32: {

            validUntil_ = input.readUInt32();
            break;
          }
          case 40: {

            optionFlags_ = input.readUInt32();
            break;
          }
          case 50: {
            ProductRecord.Builder subBuilder = null;
            if (product_ != null) {
              subBuilder = product_.toBuilder();
            }
            product_ = input.readMessage(ProductRecord.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(product_);
              product_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            PassengerRecord.Builder subBuilder = null;
            if (passenger_ != null) {
              subBuilder = passenger_.toBuilder();
            }
            passenger_ = input.readMessage(PassengerRecord.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(passenger_);
              passenger_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            Relation.Builder subBuilder = null;
            if (areaInfoCase_ == 8) {
              subBuilder = ((Relation) areaInfo_).toBuilder();
            }
            areaInfo_ =
                input.readMessage(Relation.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((Relation) areaInfo_);
              areaInfo_ = subBuilder.buildPartial();
            }
            areaInfoCase_ = 8;
            break;
          }
          case 74: {
            AreaList.Builder subBuilder = null;
            if (areaInfoCase_ == 9) {
              subBuilder = ((AreaList) areaInfo_).toBuilder();
            }
            areaInfo_ =
                input.readMessage(AreaList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((AreaList) areaInfo_);
              areaInfo_ = subBuilder.buildPartial();
            }
            areaInfoCase_ = 9;
            break;
          }
          case 82: {
            StopList.Builder subBuilder = null;
            if (areaInfoCase_ == 10) {
              subBuilder = ((StopList) areaInfo_).toBuilder();
            }
            areaInfo_ =
                input.readMessage(StopList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((StopList) areaInfo_);
              areaInfo_ = subBuilder.buildPartial();
            }
            areaInfoCase_ = 10;
            break;
          }
          case 88: {

            price_ = input.readUInt32();
            break;
          }
          case 96: {

            tax_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return OpenTicket.internal_static_OpenTicket_Legitimation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return OpenTicket.internal_static_OpenTicket_Legitimation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Legitimation.class, Legitimation.Builder.class);
  }

  private int areaInfoCase_ = 0;
  private java.lang.Object areaInfo_;
  public enum AreaInfoCase
      implements com.google.protobuf.Internal.EnumLite {
    RELATION(8),
    AREALIST(9),
    STOPLIST(10),
    AREAINFO_NOT_SET(0);
    private final int value;
    private AreaInfoCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AreaInfoCase valueOf(int value) {
      return forNumber(value);
    }

    public static AreaInfoCase forNumber(int value) {
      switch (value) {
        case 8: return RELATION;
        case 9: return AREALIST;
        case 10: return STOPLIST;
        case 0: return AREAINFO_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public AreaInfoCase
  getAreaInfoCase() {
    return AreaInfoCase.forNumber(
        areaInfoCase_);
  }

  public static final int LEGITIMATIONID_FIELD_NUMBER = 1;
  private int legitimationId_;
  /**
   * <pre>
   * the system unique legitimation id
   * </pre>
   *
   * <code>uint32 legitimationId = 1;</code>
   */
  public int getLegitimationId() {
    return legitimationId_;
  }

  public static final int DATETIMEOFORDER_FIELD_NUMBER = 2;
  private int dateTimeOfOrder_;
  /**
   * <pre>
   * the timestamp when the legitimation has been ordered
   * </pre>
   *
   * <code>uint32 dateTimeOfOrder = 2;</code>
   */
  public int getDateTimeOfOrder() {
    return dateTimeOfOrder_;
  }

  public static final int VALIDFROM_FIELD_NUMBER = 3;
  private int validFrom_;
  /**
   * <pre>
   * earliest validity timestamp of the legitimation
   * </pre>
   *
   * <code>uint32 validFrom = 3;</code>
   */
  public int getValidFrom() {
    return validFrom_;
  }

  public static final int VALIDUNTIL_FIELD_NUMBER = 4;
  private int validUntil_;
  /**
   * <pre>
   * least validity timestamp of the legitimation
   * </pre>
   *
   * <code>uint32 validUntil = 4;</code>
   */
  public int getValidUntil() {
    return validUntil_;
  }

  public static final int OPTIONFLAGS_FIELD_NUMBER = 5;
  private int optionFlags_;
  /**
   * <pre>
   * user defined option flags with 32 bits
   * </pre>
   *
   * <code>uint32 optionFlags = 5;</code>
   */
  public int getOptionFlags() {
    return optionFlags_;
  }

  public static final int PRODUCT_FIELD_NUMBER = 6;
  private ProductRecord product_;
  /**
   * <pre>
   * product record with fare product information
   * </pre>
   *
   * <code>.OpenTicket.ProductRecord product = 6;</code>
   */
  public boolean hasProduct() {
    return product_ != null;
  }
  /**
   * <pre>
   * product record with fare product information
   * </pre>
   *
   * <code>.OpenTicket.ProductRecord product = 6;</code>
   */
  public ProductRecord getProduct() {
    return product_ == null ? ProductRecord.getDefaultInstance() : product_;
  }
  /**
   * <pre>
   * product record with fare product information
   * </pre>
   *
   * <code>.OpenTicket.ProductRecord product = 6;</code>
   */
  public ProductRecordOrBuilder getProductOrBuilder() {
    return getProduct();
  }

  public static final int PASSENGER_FIELD_NUMBER = 7;
  private PassengerRecord passenger_;
  /**
   * <pre>
   * passenger record with information about how many people traveling on this legitmation
   * </pre>
   *
   * <code>.OpenTicket.PassengerRecord passenger = 7;</code>
   */
  public boolean hasPassenger() {
    return passenger_ != null;
  }
  /**
   * <pre>
   * passenger record with information about how many people traveling on this legitmation
   * </pre>
   *
   * <code>.OpenTicket.PassengerRecord passenger = 7;</code>
   */
  public PassengerRecord getPassenger() {
    return passenger_ == null ? PassengerRecord.getDefaultInstance() : passenger_;
  }
  /**
   * <pre>
   * passenger record with information about how many people traveling on this legitmation
   * </pre>
   *
   * <code>.OpenTicket.PassengerRecord passenger = 7;</code>
   */
  public PassengerRecordOrBuilder getPassengerOrBuilder() {
    return getPassenger();
  }

  public static final int RELATION_FIELD_NUMBER = 8;
  /**
   * <code>.OpenTicket.Relation relation = 8;</code>
   */
  public boolean hasRelation() {
    return areaInfoCase_ == 8;
  }
  /**
   * <code>.OpenTicket.Relation relation = 8;</code>
   */
  public Relation getRelation() {
    if (areaInfoCase_ == 8) {
       return (Relation) areaInfo_;
    }
    return Relation.getDefaultInstance();
  }
  /**
   * <code>.OpenTicket.Relation relation = 8;</code>
   */
  public RelationOrBuilder getRelationOrBuilder() {
    if (areaInfoCase_ == 8) {
       return (Relation) areaInfo_;
    }
    return Relation.getDefaultInstance();
  }

  public static final int AREALIST_FIELD_NUMBER = 9;
  /**
   * <code>.OpenTicket.AreaList areaList = 9;</code>
   */
  public boolean hasAreaList() {
    return areaInfoCase_ == 9;
  }
  /**
   * <code>.OpenTicket.AreaList areaList = 9;</code>
   */
  public AreaList getAreaList() {
    if (areaInfoCase_ == 9) {
       return (AreaList) areaInfo_;
    }
    return AreaList.getDefaultInstance();
  }
  /**
   * <code>.OpenTicket.AreaList areaList = 9;</code>
   */
  public AreaListOrBuilder getAreaListOrBuilder() {
    if (areaInfoCase_ == 9) {
       return (AreaList) areaInfo_;
    }
    return AreaList.getDefaultInstance();
  }

  public static final int STOPLIST_FIELD_NUMBER = 10;
  /**
   * <code>.OpenTicket.StopList stopList = 10;</code>
   */
  public boolean hasStopList() {
    return areaInfoCase_ == 10;
  }
  /**
   * <code>.OpenTicket.StopList stopList = 10;</code>
   */
  public StopList getStopList() {
    if (areaInfoCase_ == 10) {
       return (StopList) areaInfo_;
    }
    return StopList.getDefaultInstance();
  }
  /**
   * <code>.OpenTicket.StopList stopList = 10;</code>
   */
  public StopListOrBuilder getStopListOrBuilder() {
    if (areaInfoCase_ == 10) {
       return (StopList) areaInfo_;
    }
    return StopList.getDefaultInstance();
  }

  public static final int PRICE_FIELD_NUMBER = 11;
  private int price_;
  /**
   * <pre>
   * full price of the ticket including the tax
   * </pre>
   *
   * <code>uint32 price = 11;</code>
   */
  public int getPrice() {
    return price_;
  }

  public static final int TAX_FIELD_NUMBER = 12;
  private int tax_;
  /**
   * <pre>
   * the tax amount applied on the full price
   * </pre>
   *
   * <code>uint32 tax = 12;</code>
   */
  public int getTax() {
    return tax_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (legitimationId_ != 0) {
      output.writeUInt32(1, legitimationId_);
    }
    if (dateTimeOfOrder_ != 0) {
      output.writeUInt32(2, dateTimeOfOrder_);
    }
    if (validFrom_ != 0) {
      output.writeUInt32(3, validFrom_);
    }
    if (validUntil_ != 0) {
      output.writeUInt32(4, validUntil_);
    }
    if (optionFlags_ != 0) {
      output.writeUInt32(5, optionFlags_);
    }
    if (product_ != null) {
      output.writeMessage(6, getProduct());
    }
    if (passenger_ != null) {
      output.writeMessage(7, getPassenger());
    }
    if (areaInfoCase_ == 8) {
      output.writeMessage(8, (Relation) areaInfo_);
    }
    if (areaInfoCase_ == 9) {
      output.writeMessage(9, (AreaList) areaInfo_);
    }
    if (areaInfoCase_ == 10) {
      output.writeMessage(10, (StopList) areaInfo_);
    }
    if (price_ != 0) {
      output.writeUInt32(11, price_);
    }
    if (tax_ != 0) {
      output.writeUInt32(12, tax_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (legitimationId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, legitimationId_);
    }
    if (dateTimeOfOrder_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, dateTimeOfOrder_);
    }
    if (validFrom_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, validFrom_);
    }
    if (validUntil_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, validUntil_);
    }
    if (optionFlags_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, optionFlags_);
    }
    if (product_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getProduct());
    }
    if (passenger_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getPassenger());
    }
    if (areaInfoCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (Relation) areaInfo_);
    }
    if (areaInfoCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (AreaList) areaInfo_);
    }
    if (areaInfoCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (StopList) areaInfo_);
    }
    if (price_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(11, price_);
    }
    if (tax_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(12, tax_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Legitimation)) {
      return super.equals(obj);
    }
    Legitimation other = (Legitimation) obj;

    boolean result = true;
    result = result && (getLegitimationId()
        == other.getLegitimationId());
    result = result && (getDateTimeOfOrder()
        == other.getDateTimeOfOrder());
    result = result && (getValidFrom()
        == other.getValidFrom());
    result = result && (getValidUntil()
        == other.getValidUntil());
    result = result && (getOptionFlags()
        == other.getOptionFlags());
    result = result && (hasProduct() == other.hasProduct());
    if (hasProduct()) {
      result = result && getProduct()
          .equals(other.getProduct());
    }
    result = result && (hasPassenger() == other.hasPassenger());
    if (hasPassenger()) {
      result = result && getPassenger()
          .equals(other.getPassenger());
    }
    result = result && (getPrice()
        == other.getPrice());
    result = result && (getTax()
        == other.getTax());
    result = result && getAreaInfoCase().equals(
        other.getAreaInfoCase());
    if (!result) return false;
    switch (areaInfoCase_) {
      case 8:
        result = result && getRelation()
            .equals(other.getRelation());
        break;
      case 9:
        result = result && getAreaList()
            .equals(other.getAreaList());
        break;
      case 10:
        result = result && getStopList()
            .equals(other.getStopList());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LEGITIMATIONID_FIELD_NUMBER;
    hash = (53 * hash) + getLegitimationId();
    hash = (37 * hash) + DATETIMEOFORDER_FIELD_NUMBER;
    hash = (53 * hash) + getDateTimeOfOrder();
    hash = (37 * hash) + VALIDFROM_FIELD_NUMBER;
    hash = (53 * hash) + getValidFrom();
    hash = (37 * hash) + VALIDUNTIL_FIELD_NUMBER;
    hash = (53 * hash) + getValidUntil();
    hash = (37 * hash) + OPTIONFLAGS_FIELD_NUMBER;
    hash = (53 * hash) + getOptionFlags();
    if (hasProduct()) {
      hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
      hash = (53 * hash) + getProduct().hashCode();
    }
    if (hasPassenger()) {
      hash = (37 * hash) + PASSENGER_FIELD_NUMBER;
      hash = (53 * hash) + getPassenger().hashCode();
    }
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getPrice();
    hash = (37 * hash) + TAX_FIELD_NUMBER;
    hash = (53 * hash) + getTax();
    switch (areaInfoCase_) {
      case 8:
        hash = (37 * hash) + RELATION_FIELD_NUMBER;
        hash = (53 * hash) + getRelation().hashCode();
        break;
      case 9:
        hash = (37 * hash) + AREALIST_FIELD_NUMBER;
        hash = (53 * hash) + getAreaList().hashCode();
        break;
      case 10:
        hash = (37 * hash) + STOPLIST_FIELD_NUMBER;
        hash = (53 * hash) + getStopList().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Legitimation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Legitimation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Legitimation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Legitimation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Legitimation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Legitimation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Legitimation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Legitimation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Legitimation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Legitimation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Legitimation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Legitimation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Legitimation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * The Legitimation message contains all required information about a legitimation
   * to use for a trip.
   * </pre>
   *
   * Protobuf type {@code OpenTicket.Legitimation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OpenTicket.Legitimation)
          LegitimationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OpenTicket.internal_static_OpenTicket_Legitimation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OpenTicket.internal_static_OpenTicket_Legitimation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Legitimation.class, Legitimation.Builder.class);
    }

    // Construct using de.openticket.Legitimation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      legitimationId_ = 0;

      dateTimeOfOrder_ = 0;

      validFrom_ = 0;

      validUntil_ = 0;

      optionFlags_ = 0;

      if (productBuilder_ == null) {
        product_ = null;
      } else {
        product_ = null;
        productBuilder_ = null;
      }
      if (passengerBuilder_ == null) {
        passenger_ = null;
      } else {
        passenger_ = null;
        passengerBuilder_ = null;
      }
      price_ = 0;

      tax_ = 0;

      areaInfoCase_ = 0;
      areaInfo_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return OpenTicket.internal_static_OpenTicket_Legitimation_descriptor;
    }

    @java.lang.Override
    public Legitimation getDefaultInstanceForType() {
      return Legitimation.getDefaultInstance();
    }

    @java.lang.Override
    public Legitimation build() {
      Legitimation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Legitimation buildPartial() {
      Legitimation result = new Legitimation(this);
      result.legitimationId_ = legitimationId_;
      result.dateTimeOfOrder_ = dateTimeOfOrder_;
      result.validFrom_ = validFrom_;
      result.validUntil_ = validUntil_;
      result.optionFlags_ = optionFlags_;
      if (productBuilder_ == null) {
        result.product_ = product_;
      } else {
        result.product_ = productBuilder_.build();
      }
      if (passengerBuilder_ == null) {
        result.passenger_ = passenger_;
      } else {
        result.passenger_ = passengerBuilder_.build();
      }
      if (areaInfoCase_ == 8) {
        if (relationBuilder_ == null) {
          result.areaInfo_ = areaInfo_;
        } else {
          result.areaInfo_ = relationBuilder_.build();
        }
      }
      if (areaInfoCase_ == 9) {
        if (areaListBuilder_ == null) {
          result.areaInfo_ = areaInfo_;
        } else {
          result.areaInfo_ = areaListBuilder_.build();
        }
      }
      if (areaInfoCase_ == 10) {
        if (stopListBuilder_ == null) {
          result.areaInfo_ = areaInfo_;
        } else {
          result.areaInfo_ = stopListBuilder_.build();
        }
      }
      result.price_ = price_;
      result.tax_ = tax_;
      result.areaInfoCase_ = areaInfoCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Legitimation) {
        return mergeFrom((Legitimation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Legitimation other) {
      if (other == Legitimation.getDefaultInstance()) return this;
      if (other.getLegitimationId() != 0) {
        setLegitimationId(other.getLegitimationId());
      }
      if (other.getDateTimeOfOrder() != 0) {
        setDateTimeOfOrder(other.getDateTimeOfOrder());
      }
      if (other.getValidFrom() != 0) {
        setValidFrom(other.getValidFrom());
      }
      if (other.getValidUntil() != 0) {
        setValidUntil(other.getValidUntil());
      }
      if (other.getOptionFlags() != 0) {
        setOptionFlags(other.getOptionFlags());
      }
      if (other.hasProduct()) {
        mergeProduct(other.getProduct());
      }
      if (other.hasPassenger()) {
        mergePassenger(other.getPassenger());
      }
      if (other.getPrice() != 0) {
        setPrice(other.getPrice());
      }
      if (other.getTax() != 0) {
        setTax(other.getTax());
      }
      switch (other.getAreaInfoCase()) {
        case RELATION: {
          mergeRelation(other.getRelation());
          break;
        }
        case AREALIST: {
          mergeAreaList(other.getAreaList());
          break;
        }
        case STOPLIST: {
          mergeStopList(other.getStopList());
          break;
        }
        case AREAINFO_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Legitimation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Legitimation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int areaInfoCase_ = 0;
    private java.lang.Object areaInfo_;
    public AreaInfoCase
        getAreaInfoCase() {
      return AreaInfoCase.forNumber(
          areaInfoCase_);
    }

    public Builder clearAreaInfo() {
      areaInfoCase_ = 0;
      areaInfo_ = null;
      onChanged();
      return this;
    }


    private int legitimationId_ ;
    /**
     * <pre>
     * the system unique legitimation id
     * </pre>
     *
     * <code>uint32 legitimationId = 1;</code>
     */
    public int getLegitimationId() {
      return legitimationId_;
    }
    /**
     * <pre>
     * the system unique legitimation id
     * </pre>
     *
     * <code>uint32 legitimationId = 1;</code>
     */
    public Builder setLegitimationId(int value) {
      
      legitimationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the system unique legitimation id
     * </pre>
     *
     * <code>uint32 legitimationId = 1;</code>
     */
    public Builder clearLegitimationId() {
      
      legitimationId_ = 0;
      onChanged();
      return this;
    }

    private int dateTimeOfOrder_ ;
    /**
     * <pre>
     * the timestamp when the legitimation has been ordered
     * </pre>
     *
     * <code>uint32 dateTimeOfOrder = 2;</code>
     */
    public int getDateTimeOfOrder() {
      return dateTimeOfOrder_;
    }
    /**
     * <pre>
     * the timestamp when the legitimation has been ordered
     * </pre>
     *
     * <code>uint32 dateTimeOfOrder = 2;</code>
     */
    public Builder setDateTimeOfOrder(int value) {
      
      dateTimeOfOrder_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the timestamp when the legitimation has been ordered
     * </pre>
     *
     * <code>uint32 dateTimeOfOrder = 2;</code>
     */
    public Builder clearDateTimeOfOrder() {
      
      dateTimeOfOrder_ = 0;
      onChanged();
      return this;
    }

    private int validFrom_ ;
    /**
     * <pre>
     * earliest validity timestamp of the legitimation
     * </pre>
     *
     * <code>uint32 validFrom = 3;</code>
     */
    public int getValidFrom() {
      return validFrom_;
    }
    /**
     * <pre>
     * earliest validity timestamp of the legitimation
     * </pre>
     *
     * <code>uint32 validFrom = 3;</code>
     */
    public Builder setValidFrom(int value) {
      
      validFrom_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * earliest validity timestamp of the legitimation
     * </pre>
     *
     * <code>uint32 validFrom = 3;</code>
     */
    public Builder clearValidFrom() {
      
      validFrom_ = 0;
      onChanged();
      return this;
    }

    private int validUntil_ ;
    /**
     * <pre>
     * least validity timestamp of the legitimation
     * </pre>
     *
     * <code>uint32 validUntil = 4;</code>
     */
    public int getValidUntil() {
      return validUntil_;
    }
    /**
     * <pre>
     * least validity timestamp of the legitimation
     * </pre>
     *
     * <code>uint32 validUntil = 4;</code>
     */
    public Builder setValidUntil(int value) {
      
      validUntil_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * least validity timestamp of the legitimation
     * </pre>
     *
     * <code>uint32 validUntil = 4;</code>
     */
    public Builder clearValidUntil() {
      
      validUntil_ = 0;
      onChanged();
      return this;
    }

    private int optionFlags_ ;
    /**
     * <pre>
     * user defined option flags with 32 bits
     * </pre>
     *
     * <code>uint32 optionFlags = 5;</code>
     */
    public int getOptionFlags() {
      return optionFlags_;
    }
    /**
     * <pre>
     * user defined option flags with 32 bits
     * </pre>
     *
     * <code>uint32 optionFlags = 5;</code>
     */
    public Builder setOptionFlags(int value) {
      
      optionFlags_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * user defined option flags with 32 bits
     * </pre>
     *
     * <code>uint32 optionFlags = 5;</code>
     */
    public Builder clearOptionFlags() {
      
      optionFlags_ = 0;
      onChanged();
      return this;
    }

    private ProductRecord product_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            ProductRecord, ProductRecord.Builder, ProductRecordOrBuilder> productBuilder_;
    /**
     * <pre>
     * product record with fare product information
     * </pre>
     *
     * <code>.OpenTicket.ProductRecord product = 6;</code>
     */
    public boolean hasProduct() {
      return productBuilder_ != null || product_ != null;
    }
    /**
     * <pre>
     * product record with fare product information
     * </pre>
     *
     * <code>.OpenTicket.ProductRecord product = 6;</code>
     */
    public ProductRecord getProduct() {
      if (productBuilder_ == null) {
        return product_ == null ? ProductRecord.getDefaultInstance() : product_;
      } else {
        return productBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * product record with fare product information
     * </pre>
     *
     * <code>.OpenTicket.ProductRecord product = 6;</code>
     */
    public Builder setProduct(ProductRecord value) {
      if (productBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        product_ = value;
        onChanged();
      } else {
        productBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * product record with fare product information
     * </pre>
     *
     * <code>.OpenTicket.ProductRecord product = 6;</code>
     */
    public Builder setProduct(
        ProductRecord.Builder builderForValue) {
      if (productBuilder_ == null) {
        product_ = builderForValue.build();
        onChanged();
      } else {
        productBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * product record with fare product information
     * </pre>
     *
     * <code>.OpenTicket.ProductRecord product = 6;</code>
     */
    public Builder mergeProduct(ProductRecord value) {
      if (productBuilder_ == null) {
        if (product_ != null) {
          product_ =
            ProductRecord.newBuilder(product_).mergeFrom(value).buildPartial();
        } else {
          product_ = value;
        }
        onChanged();
      } else {
        productBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * product record with fare product information
     * </pre>
     *
     * <code>.OpenTicket.ProductRecord product = 6;</code>
     */
    public Builder clearProduct() {
      if (productBuilder_ == null) {
        product_ = null;
        onChanged();
      } else {
        product_ = null;
        productBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * product record with fare product information
     * </pre>
     *
     * <code>.OpenTicket.ProductRecord product = 6;</code>
     */
    public ProductRecord.Builder getProductBuilder() {
      
      onChanged();
      return getProductFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * product record with fare product information
     * </pre>
     *
     * <code>.OpenTicket.ProductRecord product = 6;</code>
     */
    public ProductRecordOrBuilder getProductOrBuilder() {
      if (productBuilder_ != null) {
        return productBuilder_.getMessageOrBuilder();
      } else {
        return product_ == null ?
            ProductRecord.getDefaultInstance() : product_;
      }
    }
    /**
     * <pre>
     * product record with fare product information
     * </pre>
     *
     * <code>.OpenTicket.ProductRecord product = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            ProductRecord, ProductRecord.Builder, ProductRecordOrBuilder>
        getProductFieldBuilder() {
      if (productBuilder_ == null) {
        productBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                ProductRecord, ProductRecord.Builder, ProductRecordOrBuilder>(
                getProduct(),
                getParentForChildren(),
                isClean());
        product_ = null;
      }
      return productBuilder_;
    }

    private PassengerRecord passenger_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            PassengerRecord, PassengerRecord.Builder, PassengerRecordOrBuilder> passengerBuilder_;
    /**
     * <pre>
     * passenger record with information about how many people traveling on this legitmation
     * </pre>
     *
     * <code>.OpenTicket.PassengerRecord passenger = 7;</code>
     */
    public boolean hasPassenger() {
      return passengerBuilder_ != null || passenger_ != null;
    }
    /**
     * <pre>
     * passenger record with information about how many people traveling on this legitmation
     * </pre>
     *
     * <code>.OpenTicket.PassengerRecord passenger = 7;</code>
     */
    public PassengerRecord getPassenger() {
      if (passengerBuilder_ == null) {
        return passenger_ == null ? PassengerRecord.getDefaultInstance() : passenger_;
      } else {
        return passengerBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * passenger record with information about how many people traveling on this legitmation
     * </pre>
     *
     * <code>.OpenTicket.PassengerRecord passenger = 7;</code>
     */
    public Builder setPassenger(PassengerRecord value) {
      if (passengerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        passenger_ = value;
        onChanged();
      } else {
        passengerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * passenger record with information about how many people traveling on this legitmation
     * </pre>
     *
     * <code>.OpenTicket.PassengerRecord passenger = 7;</code>
     */
    public Builder setPassenger(
        PassengerRecord.Builder builderForValue) {
      if (passengerBuilder_ == null) {
        passenger_ = builderForValue.build();
        onChanged();
      } else {
        passengerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * passenger record with information about how many people traveling on this legitmation
     * </pre>
     *
     * <code>.OpenTicket.PassengerRecord passenger = 7;</code>
     */
    public Builder mergePassenger(PassengerRecord value) {
      if (passengerBuilder_ == null) {
        if (passenger_ != null) {
          passenger_ =
            PassengerRecord.newBuilder(passenger_).mergeFrom(value).buildPartial();
        } else {
          passenger_ = value;
        }
        onChanged();
      } else {
        passengerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * passenger record with information about how many people traveling on this legitmation
     * </pre>
     *
     * <code>.OpenTicket.PassengerRecord passenger = 7;</code>
     */
    public Builder clearPassenger() {
      if (passengerBuilder_ == null) {
        passenger_ = null;
        onChanged();
      } else {
        passenger_ = null;
        passengerBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * passenger record with information about how many people traveling on this legitmation
     * </pre>
     *
     * <code>.OpenTicket.PassengerRecord passenger = 7;</code>
     */
    public PassengerRecord.Builder getPassengerBuilder() {
      
      onChanged();
      return getPassengerFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * passenger record with information about how many people traveling on this legitmation
     * </pre>
     *
     * <code>.OpenTicket.PassengerRecord passenger = 7;</code>
     */
    public PassengerRecordOrBuilder getPassengerOrBuilder() {
      if (passengerBuilder_ != null) {
        return passengerBuilder_.getMessageOrBuilder();
      } else {
        return passenger_ == null ?
            PassengerRecord.getDefaultInstance() : passenger_;
      }
    }
    /**
     * <pre>
     * passenger record with information about how many people traveling on this legitmation
     * </pre>
     *
     * <code>.OpenTicket.PassengerRecord passenger = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            PassengerRecord, PassengerRecord.Builder, PassengerRecordOrBuilder>
        getPassengerFieldBuilder() {
      if (passengerBuilder_ == null) {
        passengerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                PassengerRecord, PassengerRecord.Builder, PassengerRecordOrBuilder>(
                getPassenger(),
                getParentForChildren(),
                isClean());
        passenger_ = null;
      }
      return passengerBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
            Relation, Relation.Builder, RelationOrBuilder> relationBuilder_;
    /**
     * <code>.OpenTicket.Relation relation = 8;</code>
     */
    public boolean hasRelation() {
      return areaInfoCase_ == 8;
    }
    /**
     * <code>.OpenTicket.Relation relation = 8;</code>
     */
    public Relation getRelation() {
      if (relationBuilder_ == null) {
        if (areaInfoCase_ == 8) {
          return (Relation) areaInfo_;
        }
        return Relation.getDefaultInstance();
      } else {
        if (areaInfoCase_ == 8) {
          return relationBuilder_.getMessage();
        }
        return Relation.getDefaultInstance();
      }
    }
    /**
     * <code>.OpenTicket.Relation relation = 8;</code>
     */
    public Builder setRelation(Relation value) {
      if (relationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        areaInfo_ = value;
        onChanged();
      } else {
        relationBuilder_.setMessage(value);
      }
      areaInfoCase_ = 8;
      return this;
    }
    /**
     * <code>.OpenTicket.Relation relation = 8;</code>
     */
    public Builder setRelation(
        Relation.Builder builderForValue) {
      if (relationBuilder_ == null) {
        areaInfo_ = builderForValue.build();
        onChanged();
      } else {
        relationBuilder_.setMessage(builderForValue.build());
      }
      areaInfoCase_ = 8;
      return this;
    }
    /**
     * <code>.OpenTicket.Relation relation = 8;</code>
     */
    public Builder mergeRelation(Relation value) {
      if (relationBuilder_ == null) {
        if (areaInfoCase_ == 8 &&
            areaInfo_ != Relation.getDefaultInstance()) {
          areaInfo_ = Relation.newBuilder((Relation) areaInfo_)
              .mergeFrom(value).buildPartial();
        } else {
          areaInfo_ = value;
        }
        onChanged();
      } else {
        if (areaInfoCase_ == 8) {
          relationBuilder_.mergeFrom(value);
        }
        relationBuilder_.setMessage(value);
      }
      areaInfoCase_ = 8;
      return this;
    }
    /**
     * <code>.OpenTicket.Relation relation = 8;</code>
     */
    public Builder clearRelation() {
      if (relationBuilder_ == null) {
        if (areaInfoCase_ == 8) {
          areaInfoCase_ = 0;
          areaInfo_ = null;
          onChanged();
        }
      } else {
        if (areaInfoCase_ == 8) {
          areaInfoCase_ = 0;
          areaInfo_ = null;
        }
        relationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.OpenTicket.Relation relation = 8;</code>
     */
    public Relation.Builder getRelationBuilder() {
      return getRelationFieldBuilder().getBuilder();
    }
    /**
     * <code>.OpenTicket.Relation relation = 8;</code>
     */
    public RelationOrBuilder getRelationOrBuilder() {
      if ((areaInfoCase_ == 8) && (relationBuilder_ != null)) {
        return relationBuilder_.getMessageOrBuilder();
      } else {
        if (areaInfoCase_ == 8) {
          return (Relation) areaInfo_;
        }
        return Relation.getDefaultInstance();
      }
    }
    /**
     * <code>.OpenTicket.Relation relation = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            Relation, Relation.Builder, RelationOrBuilder>
        getRelationFieldBuilder() {
      if (relationBuilder_ == null) {
        if (!(areaInfoCase_ == 8)) {
          areaInfo_ = Relation.getDefaultInstance();
        }
        relationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                Relation, Relation.Builder, RelationOrBuilder>(
                (Relation) areaInfo_,
                getParentForChildren(),
                isClean());
        areaInfo_ = null;
      }
      areaInfoCase_ = 8;
      onChanged();;
      return relationBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
            AreaList, AreaList.Builder, AreaListOrBuilder> areaListBuilder_;
    /**
     * <code>.OpenTicket.AreaList areaList = 9;</code>
     */
    public boolean hasAreaList() {
      return areaInfoCase_ == 9;
    }
    /**
     * <code>.OpenTicket.AreaList areaList = 9;</code>
     */
    public AreaList getAreaList() {
      if (areaListBuilder_ == null) {
        if (areaInfoCase_ == 9) {
          return (AreaList) areaInfo_;
        }
        return AreaList.getDefaultInstance();
      } else {
        if (areaInfoCase_ == 9) {
          return areaListBuilder_.getMessage();
        }
        return AreaList.getDefaultInstance();
      }
    }
    /**
     * <code>.OpenTicket.AreaList areaList = 9;</code>
     */
    public Builder setAreaList(AreaList value) {
      if (areaListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        areaInfo_ = value;
        onChanged();
      } else {
        areaListBuilder_.setMessage(value);
      }
      areaInfoCase_ = 9;
      return this;
    }
    /**
     * <code>.OpenTicket.AreaList areaList = 9;</code>
     */
    public Builder setAreaList(
        AreaList.Builder builderForValue) {
      if (areaListBuilder_ == null) {
        areaInfo_ = builderForValue.build();
        onChanged();
      } else {
        areaListBuilder_.setMessage(builderForValue.build());
      }
      areaInfoCase_ = 9;
      return this;
    }
    /**
     * <code>.OpenTicket.AreaList areaList = 9;</code>
     */
    public Builder mergeAreaList(AreaList value) {
      if (areaListBuilder_ == null) {
        if (areaInfoCase_ == 9 &&
            areaInfo_ != AreaList.getDefaultInstance()) {
          areaInfo_ = AreaList.newBuilder((AreaList) areaInfo_)
              .mergeFrom(value).buildPartial();
        } else {
          areaInfo_ = value;
        }
        onChanged();
      } else {
        if (areaInfoCase_ == 9) {
          areaListBuilder_.mergeFrom(value);
        }
        areaListBuilder_.setMessage(value);
      }
      areaInfoCase_ = 9;
      return this;
    }
    /**
     * <code>.OpenTicket.AreaList areaList = 9;</code>
     */
    public Builder clearAreaList() {
      if (areaListBuilder_ == null) {
        if (areaInfoCase_ == 9) {
          areaInfoCase_ = 0;
          areaInfo_ = null;
          onChanged();
        }
      } else {
        if (areaInfoCase_ == 9) {
          areaInfoCase_ = 0;
          areaInfo_ = null;
        }
        areaListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.OpenTicket.AreaList areaList = 9;</code>
     */
    public AreaList.Builder getAreaListBuilder() {
      return getAreaListFieldBuilder().getBuilder();
    }
    /**
     * <code>.OpenTicket.AreaList areaList = 9;</code>
     */
    public AreaListOrBuilder getAreaListOrBuilder() {
      if ((areaInfoCase_ == 9) && (areaListBuilder_ != null)) {
        return areaListBuilder_.getMessageOrBuilder();
      } else {
        if (areaInfoCase_ == 9) {
          return (AreaList) areaInfo_;
        }
        return AreaList.getDefaultInstance();
      }
    }
    /**
     * <code>.OpenTicket.AreaList areaList = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            AreaList, AreaList.Builder, AreaListOrBuilder>
        getAreaListFieldBuilder() {
      if (areaListBuilder_ == null) {
        if (!(areaInfoCase_ == 9)) {
          areaInfo_ = AreaList.getDefaultInstance();
        }
        areaListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                AreaList, AreaList.Builder, AreaListOrBuilder>(
                (AreaList) areaInfo_,
                getParentForChildren(),
                isClean());
        areaInfo_ = null;
      }
      areaInfoCase_ = 9;
      onChanged();;
      return areaListBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
            StopList, StopList.Builder, StopListOrBuilder> stopListBuilder_;
    /**
     * <code>.OpenTicket.StopList stopList = 10;</code>
     */
    public boolean hasStopList() {
      return areaInfoCase_ == 10;
    }
    /**
     * <code>.OpenTicket.StopList stopList = 10;</code>
     */
    public StopList getStopList() {
      if (stopListBuilder_ == null) {
        if (areaInfoCase_ == 10) {
          return (StopList) areaInfo_;
        }
        return StopList.getDefaultInstance();
      } else {
        if (areaInfoCase_ == 10) {
          return stopListBuilder_.getMessage();
        }
        return StopList.getDefaultInstance();
      }
    }
    /**
     * <code>.OpenTicket.StopList stopList = 10;</code>
     */
    public Builder setStopList(StopList value) {
      if (stopListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        areaInfo_ = value;
        onChanged();
      } else {
        stopListBuilder_.setMessage(value);
      }
      areaInfoCase_ = 10;
      return this;
    }
    /**
     * <code>.OpenTicket.StopList stopList = 10;</code>
     */
    public Builder setStopList(
        StopList.Builder builderForValue) {
      if (stopListBuilder_ == null) {
        areaInfo_ = builderForValue.build();
        onChanged();
      } else {
        stopListBuilder_.setMessage(builderForValue.build());
      }
      areaInfoCase_ = 10;
      return this;
    }
    /**
     * <code>.OpenTicket.StopList stopList = 10;</code>
     */
    public Builder mergeStopList(StopList value) {
      if (stopListBuilder_ == null) {
        if (areaInfoCase_ == 10 &&
            areaInfo_ != StopList.getDefaultInstance()) {
          areaInfo_ = StopList.newBuilder((StopList) areaInfo_)
              .mergeFrom(value).buildPartial();
        } else {
          areaInfo_ = value;
        }
        onChanged();
      } else {
        if (areaInfoCase_ == 10) {
          stopListBuilder_.mergeFrom(value);
        }
        stopListBuilder_.setMessage(value);
      }
      areaInfoCase_ = 10;
      return this;
    }
    /**
     * <code>.OpenTicket.StopList stopList = 10;</code>
     */
    public Builder clearStopList() {
      if (stopListBuilder_ == null) {
        if (areaInfoCase_ == 10) {
          areaInfoCase_ = 0;
          areaInfo_ = null;
          onChanged();
        }
      } else {
        if (areaInfoCase_ == 10) {
          areaInfoCase_ = 0;
          areaInfo_ = null;
        }
        stopListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.OpenTicket.StopList stopList = 10;</code>
     */
    public StopList.Builder getStopListBuilder() {
      return getStopListFieldBuilder().getBuilder();
    }
    /**
     * <code>.OpenTicket.StopList stopList = 10;</code>
     */
    public StopListOrBuilder getStopListOrBuilder() {
      if ((areaInfoCase_ == 10) && (stopListBuilder_ != null)) {
        return stopListBuilder_.getMessageOrBuilder();
      } else {
        if (areaInfoCase_ == 10) {
          return (StopList) areaInfo_;
        }
        return StopList.getDefaultInstance();
      }
    }
    /**
     * <code>.OpenTicket.StopList stopList = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            StopList, StopList.Builder, StopListOrBuilder>
        getStopListFieldBuilder() {
      if (stopListBuilder_ == null) {
        if (!(areaInfoCase_ == 10)) {
          areaInfo_ = StopList.getDefaultInstance();
        }
        stopListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                StopList, StopList.Builder, StopListOrBuilder>(
                (StopList) areaInfo_,
                getParentForChildren(),
                isClean());
        areaInfo_ = null;
      }
      areaInfoCase_ = 10;
      onChanged();;
      return stopListBuilder_;
    }

    private int price_ ;
    /**
     * <pre>
     * full price of the ticket including the tax
     * </pre>
     *
     * <code>uint32 price = 11;</code>
     */
    public int getPrice() {
      return price_;
    }
    /**
     * <pre>
     * full price of the ticket including the tax
     * </pre>
     *
     * <code>uint32 price = 11;</code>
     */
    public Builder setPrice(int value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * full price of the ticket including the tax
     * </pre>
     *
     * <code>uint32 price = 11;</code>
     */
    public Builder clearPrice() {
      
      price_ = 0;
      onChanged();
      return this;
    }

    private int tax_ ;
    /**
     * <pre>
     * the tax amount applied on the full price
     * </pre>
     *
     * <code>uint32 tax = 12;</code>
     */
    public int getTax() {
      return tax_;
    }
    /**
     * <pre>
     * the tax amount applied on the full price
     * </pre>
     *
     * <code>uint32 tax = 12;</code>
     */
    public Builder setTax(int value) {
      
      tax_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the tax amount applied on the full price
     * </pre>
     *
     * <code>uint32 tax = 12;</code>
     */
    public Builder clearTax() {
      
      tax_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:OpenTicket.Legitimation)
  }

  // @@protoc_insertion_point(class_scope:OpenTicket.Legitimation)
  private static final Legitimation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Legitimation();
  }

  public static Legitimation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Legitimation>
      PARSER = new com.google.protobuf.AbstractParser<Legitimation>() {
    @java.lang.Override
    public Legitimation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Legitimation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Legitimation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Legitimation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Legitimation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

