// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OpenTicket.proto

package org.openticket;

public final class OpenTicket {
  private OpenTicket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenTicket_Envelope_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenTicket_Envelope_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenTicket_Legitimation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenTicket_Legitimation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenTicket_ProductRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenTicket_ProductRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenTicket_PassengerRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenTicket_PassengerRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenTicket_Relation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenTicket_Relation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenTicket_AreaList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenTicket_AreaList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenTicket_StopList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenTicket_StopList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020OpenTicket.proto\022\nOpenTicket\"T\n\010Envelo" +
      "pe\022\027\n\017envelopeVersion\030\001 \001(\r\022\017\n\007keyName\030\002" +
      " \001(\t\022\036\n\026encryptedLegitimations\030\003 \003(\014\"\375\002\n" +
      "\014Legitimation\022\026\n\016legitimationId\030\001 \001(\r\022\027\n" +
      "\017dateTimeOfOrder\030\002 \001(\r\022\021\n\tvalidFrom\030\003 \001(" +
      "\r\022\022\n\nvalidUntil\030\004 \001(\r\022\023\n\013optionFlags\030\005 \001" +
      "(\r\022*\n\007product\030\006 \001(\0132\031.OpenTicket.Product" +
      "Record\022.\n\tpassenger\030\007 \001(\0132\033.OpenTicket.P" +
      "assengerRecord\022(\n\010relation\030\010 \001(\0132\024.OpenT" +
      "icket.RelationH\000\022(\n\010areaList\030\t \001(\0132\024.Ope" +
      "nTicket.AreaListH\000\022(\n\010stopList\030\n \001(\0132\024.O" +
      "penTicket.StopListH\000\022\r\n\005price\030\013 \001(\r\022\013\n\003t" +
      "ax\030\014 \001(\rB\n\n\010AreaInfo\"E\n\rProductRecord\022\014\n" +
      "\004name\030\001 \001(\t\022\020\n\010infoText\030\002 \001(\t\022\024\n\014service" +
      "Class\030\003 \001(\r\"\313\001\n\017PassengerRecord\022\025\n\rperso" +
      "nRelated\030\001 \001(\010\022\014\n\004name\030\002 \001(\t\022\013\n\003age\030\003 \001(" +
      "\r\0222\n\006gender\030\004 \001(\0162\".OpenTicket.Passenger" +
      "Record.Gender\022\021\n\tnumAdults\030\005 \001(\r\022\023\n\013numC" +
      "hildren\030\006 \001(\r\"*\n\006Gender\022\n\n\006DIVERS\020\000\022\010\n\004M" +
      "ALE\020\001\022\n\n\006FEMALE\020\002\"U\n\010Relation\022\023\n\013startSt" +
      "opId\030\001 \001(\r\022\031\n\021destinationStopId\030\002 \001(\r\022\031\n" +
      "\021containingAreaIds\030\003 \003(\r\":\n\010AreaList\022\023\n\013" +
      "startStopId\030\001 \001(\r\022\031\n\021containingAreaIds\030\002" +
      " \003(\r\":\n\010StopList\022\023\n\013startStopId\030\001 \001(\r\022\031\n" +
      "\021containingStopIds\030\002 \003(\rB\035\n\rde.openticke" +
      "tB\nOpenTicketP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OpenTicket_Envelope_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OpenTicket_Envelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenTicket_Envelope_descriptor,
        new java.lang.String[] { "EnvelopeVersion", "KeyName", "EncryptedLegitimations", });
    internal_static_OpenTicket_Legitimation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OpenTicket_Legitimation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenTicket_Legitimation_descriptor,
        new java.lang.String[] { "LegitimationId", "DateTimeOfOrder", "ValidFrom", "ValidUntil", "OptionFlags", "Product", "Passenger", "Relation", "AreaList", "StopList", "Price", "Tax", "AreaInfo", });
    internal_static_OpenTicket_ProductRecord_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OpenTicket_ProductRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenTicket_ProductRecord_descriptor,
        new java.lang.String[] { "Name", "InfoText", "ServiceClass", });
    internal_static_OpenTicket_PassengerRecord_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_OpenTicket_PassengerRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenTicket_PassengerRecord_descriptor,
        new java.lang.String[] { "PersonRelated", "Name", "Age", "Gender", "NumAdults", "NumChildren", });
    internal_static_OpenTicket_Relation_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_OpenTicket_Relation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenTicket_Relation_descriptor,
        new java.lang.String[] { "StartStopId", "DestinationStopId", "ContainingAreaIds", });
    internal_static_OpenTicket_AreaList_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_OpenTicket_AreaList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenTicket_AreaList_descriptor,
        new java.lang.String[] { "StartStopId", "ContainingAreaIds", });
    internal_static_OpenTicket_StopList_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_OpenTicket_StopList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenTicket_StopList_descriptor,
        new java.lang.String[] { "StartStopId", "ContainingStopIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
