// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OpenTicket.proto

package org.openticket;

/**
 * <pre>
 **
 * The PassengerRecord messages defines information about the passenger who is permitted
 * to use the legitimation and other information about the passenger carriage.
 * </pre>
 *
 * Protobuf type {@code OpenTicket.PassengerRecord}
 */
public  final class PassengerRecord extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OpenTicket.PassengerRecord)
    PassengerRecordOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PassengerRecord.newBuilder() to construct.
  private PassengerRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PassengerRecord() {
    personRelated_ = false;
    name_ = "";
    age_ = 0;
    gender_ = 0;
    numAdults_ = 0;
    numChildren_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PassengerRecord(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            personRelated_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {

            age_ = input.readUInt32();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            gender_ = rawValue;
            break;
          }
          case 40: {

            numAdults_ = input.readUInt32();
            break;
          }
          case 48: {

            numChildren_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return OpenTicket.internal_static_OpenTicket_PassengerRecord_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return OpenTicket.internal_static_OpenTicket_PassengerRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PassengerRecord.class, PassengerRecord.Builder.class);
  }

  /**
   * <pre>
   * gender enumeration of all possible genders
   * </pre>
   *
   * Protobuf enum {@code OpenTicket.PassengerRecord.Gender}
   */
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DIVERS = 0;</code>
     */
    DIVERS(0),
    /**
     * <code>MALE = 1;</code>
     */
    MALE(1),
    /**
     * <code>FEMALE = 2;</code>
     */
    FEMALE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DIVERS = 0;</code>
     */
    public static final int DIVERS_VALUE = 0;
    /**
     * <code>MALE = 1;</code>
     */
    public static final int MALE_VALUE = 1;
    /**
     * <code>FEMALE = 2;</code>
     */
    public static final int FEMALE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Gender valueOf(int value) {
      return forNumber(value);
    }

    public static Gender forNumber(int value) {
      switch (value) {
        case 0: return DIVERS;
        case 1: return MALE;
        case 2: return FEMALE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return PassengerRecord.getDescriptor().getEnumTypes().get(0);
    }

    private static final Gender[] VALUES = values();

    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Gender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:OpenTicket.PassengerRecord.Gender)
  }

  public static final int PERSONRELATED_FIELD_NUMBER = 1;
  private boolean personRelated_;
  /**
   * <pre>
   * whether the legitimation is restricted to be used by a certain person
   * </pre>
   *
   * <code>bool personRelated = 1;</code>
   */
  public boolean getPersonRelated() {
    return personRelated_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * name of the passenger (should be shortened in order to save memory and match privacy!)
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * name of the passenger (should be shortened in order to save memory and match privacy!)
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 3;
  private int age_;
  /**
   * <pre>
   * age of the passenger
   * </pre>
   *
   * <code>uint32 age = 3;</code>
   */
  public int getAge() {
    return age_;
  }

  public static final int GENDER_FIELD_NUMBER = 4;
  private int gender_;
  /**
   * <pre>
   * gender of the passenger which is permitted to use the legitimation
   * </pre>
   *
   * <code>.OpenTicket.PassengerRecord.Gender gender = 4;</code>
   */
  public int getGenderValue() {
    return gender_;
  }
  /**
   * <pre>
   * gender of the passenger which is permitted to use the legitimation
   * </pre>
   *
   * <code>.OpenTicket.PassengerRecord.Gender gender = 4;</code>
   */
  public PassengerRecord.Gender getGender() {
    @SuppressWarnings("deprecation")
    PassengerRecord.Gender result = PassengerRecord.Gender.valueOf(gender_);
    return result == null ? PassengerRecord.Gender.UNRECOGNIZED : result;
  }

  public static final int NUMADULTS_FIELD_NUMBER = 5;
  private int numAdults_;
  /**
   * <pre>
   * number of adult passengers
   * </pre>
   *
   * <code>uint32 numAdults = 5;</code>
   */
  public int getNumAdults() {
    return numAdults_;
  }

  public static final int NUMCHILDREN_FIELD_NUMBER = 6;
  private int numChildren_;
  /**
   * <pre>
   * number of children
   * </pre>
   *
   * <code>uint32 numChildren = 6;</code>
   */
  public int getNumChildren() {
    return numChildren_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (personRelated_ != false) {
      output.writeBool(1, personRelated_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (age_ != 0) {
      output.writeUInt32(3, age_);
    }
    if (gender_ != PassengerRecord.Gender.DIVERS.getNumber()) {
      output.writeEnum(4, gender_);
    }
    if (numAdults_ != 0) {
      output.writeUInt32(5, numAdults_);
    }
    if (numChildren_ != 0) {
      output.writeUInt32(6, numChildren_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (personRelated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, personRelated_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, age_);
    }
    if (gender_ != PassengerRecord.Gender.DIVERS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, gender_);
    }
    if (numAdults_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, numAdults_);
    }
    if (numChildren_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, numChildren_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PassengerRecord)) {
      return super.equals(obj);
    }
    PassengerRecord other = (PassengerRecord) obj;

    boolean result = true;
    result = result && (getPersonRelated()
        == other.getPersonRelated());
    result = result && getName()
        .equals(other.getName());
    result = result && (getAge()
        == other.getAge());
    result = result && gender_ == other.gender_;
    result = result && (getNumAdults()
        == other.getNumAdults());
    result = result && (getNumChildren()
        == other.getNumChildren());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PERSONRELATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPersonRelated());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    hash = (37 * hash) + GENDER_FIELD_NUMBER;
    hash = (53 * hash) + gender_;
    hash = (37 * hash) + NUMADULTS_FIELD_NUMBER;
    hash = (53 * hash) + getNumAdults();
    hash = (37 * hash) + NUMCHILDREN_FIELD_NUMBER;
    hash = (53 * hash) + getNumChildren();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PassengerRecord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PassengerRecord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PassengerRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PassengerRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PassengerRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PassengerRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PassengerRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PassengerRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static PassengerRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static PassengerRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PassengerRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PassengerRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PassengerRecord prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * The PassengerRecord messages defines information about the passenger who is permitted
   * to use the legitimation and other information about the passenger carriage.
   * </pre>
   *
   * Protobuf type {@code OpenTicket.PassengerRecord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OpenTicket.PassengerRecord)
          PassengerRecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OpenTicket.internal_static_OpenTicket_PassengerRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OpenTicket.internal_static_OpenTicket_PassengerRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PassengerRecord.class, PassengerRecord.Builder.class);
    }

    // Construct using de.openticket.PassengerRecord.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      personRelated_ = false;

      name_ = "";

      age_ = 0;

      gender_ = 0;

      numAdults_ = 0;

      numChildren_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return OpenTicket.internal_static_OpenTicket_PassengerRecord_descriptor;
    }

    @java.lang.Override
    public PassengerRecord getDefaultInstanceForType() {
      return PassengerRecord.getDefaultInstance();
    }

    @java.lang.Override
    public PassengerRecord build() {
      PassengerRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public PassengerRecord buildPartial() {
      PassengerRecord result = new PassengerRecord(this);
      result.personRelated_ = personRelated_;
      result.name_ = name_;
      result.age_ = age_;
      result.gender_ = gender_;
      result.numAdults_ = numAdults_;
      result.numChildren_ = numChildren_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PassengerRecord) {
        return mergeFrom((PassengerRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PassengerRecord other) {
      if (other == PassengerRecord.getDefaultInstance()) return this;
      if (other.getPersonRelated() != false) {
        setPersonRelated(other.getPersonRelated());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (other.gender_ != 0) {
        setGenderValue(other.getGenderValue());
      }
      if (other.getNumAdults() != 0) {
        setNumAdults(other.getNumAdults());
      }
      if (other.getNumChildren() != 0) {
        setNumChildren(other.getNumChildren());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      PassengerRecord parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (PassengerRecord) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean personRelated_ ;
    /**
     * <pre>
     * whether the legitimation is restricted to be used by a certain person
     * </pre>
     *
     * <code>bool personRelated = 1;</code>
     */
    public boolean getPersonRelated() {
      return personRelated_;
    }
    /**
     * <pre>
     * whether the legitimation is restricted to be used by a certain person
     * </pre>
     *
     * <code>bool personRelated = 1;</code>
     */
    public Builder setPersonRelated(boolean value) {
      
      personRelated_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * whether the legitimation is restricted to be used by a certain person
     * </pre>
     *
     * <code>bool personRelated = 1;</code>
     */
    public Builder clearPersonRelated() {
      
      personRelated_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * name of the passenger (should be shortened in order to save memory and match privacy!)
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * name of the passenger (should be shortened in order to save memory and match privacy!)
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * name of the passenger (should be shortened in order to save memory and match privacy!)
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name of the passenger (should be shortened in order to save memory and match privacy!)
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name of the passenger (should be shortened in order to save memory and match privacy!)
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <pre>
     * age of the passenger
     * </pre>
     *
     * <code>uint32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }
    /**
     * <pre>
     * age of the passenger
     * </pre>
     *
     * <code>uint32 age = 3;</code>
     */
    public Builder setAge(int value) {
      
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * age of the passenger
     * </pre>
     *
     * <code>uint32 age = 3;</code>
     */
    public Builder clearAge() {
      
      age_ = 0;
      onChanged();
      return this;
    }

    private int gender_ = 0;
    /**
     * <pre>
     * gender of the passenger which is permitted to use the legitimation
     * </pre>
     *
     * <code>.OpenTicket.PassengerRecord.Gender gender = 4;</code>
     */
    public int getGenderValue() {
      return gender_;
    }
    /**
     * <pre>
     * gender of the passenger which is permitted to use the legitimation
     * </pre>
     *
     * <code>.OpenTicket.PassengerRecord.Gender gender = 4;</code>
     */
    public Builder setGenderValue(int value) {
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * gender of the passenger which is permitted to use the legitimation
     * </pre>
     *
     * <code>.OpenTicket.PassengerRecord.Gender gender = 4;</code>
     */
    public PassengerRecord.Gender getGender() {
      @SuppressWarnings("deprecation")
      PassengerRecord.Gender result = PassengerRecord.Gender.valueOf(gender_);
      return result == null ? PassengerRecord.Gender.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * gender of the passenger which is permitted to use the legitimation
     * </pre>
     *
     * <code>.OpenTicket.PassengerRecord.Gender gender = 4;</code>
     */
    public Builder setGender(PassengerRecord.Gender value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      gender_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * gender of the passenger which is permitted to use the legitimation
     * </pre>
     *
     * <code>.OpenTicket.PassengerRecord.Gender gender = 4;</code>
     */
    public Builder clearGender() {
      
      gender_ = 0;
      onChanged();
      return this;
    }

    private int numAdults_ ;
    /**
     * <pre>
     * number of adult passengers
     * </pre>
     *
     * <code>uint32 numAdults = 5;</code>
     */
    public int getNumAdults() {
      return numAdults_;
    }
    /**
     * <pre>
     * number of adult passengers
     * </pre>
     *
     * <code>uint32 numAdults = 5;</code>
     */
    public Builder setNumAdults(int value) {
      
      numAdults_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * number of adult passengers
     * </pre>
     *
     * <code>uint32 numAdults = 5;</code>
     */
    public Builder clearNumAdults() {
      
      numAdults_ = 0;
      onChanged();
      return this;
    }

    private int numChildren_ ;
    /**
     * <pre>
     * number of children
     * </pre>
     *
     * <code>uint32 numChildren = 6;</code>
     */
    public int getNumChildren() {
      return numChildren_;
    }
    /**
     * <pre>
     * number of children
     * </pre>
     *
     * <code>uint32 numChildren = 6;</code>
     */
    public Builder setNumChildren(int value) {
      
      numChildren_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * number of children
     * </pre>
     *
     * <code>uint32 numChildren = 6;</code>
     */
    public Builder clearNumChildren() {
      
      numChildren_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:OpenTicket.PassengerRecord)
  }

  // @@protoc_insertion_point(class_scope:OpenTicket.PassengerRecord)
  private static final PassengerRecord DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PassengerRecord();
  }

  public static PassengerRecord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PassengerRecord>
      PARSER = new com.google.protobuf.AbstractParser<PassengerRecord>() {
    @java.lang.Override
    public PassengerRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PassengerRecord(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PassengerRecord> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PassengerRecord> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public PassengerRecord getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

