// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OpenTicket.proto

package org.openticket;

public interface PassengerRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OpenTicket.PassengerRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * whether the legitimation is restricted to be used by a certain person
   * </pre>
   *
   * <code>bool personRelated = 1;</code>
   */
  boolean getPersonRelated();

  /**
   * <pre>
   * name of the passenger (should be shortened in order to save memory and match privacy!)
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * name of the passenger (should be shortened in order to save memory and match privacy!)
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * age of the passenger
   * </pre>
   *
   * <code>uint32 age = 3;</code>
   */
  int getAge();

  /**
   * <pre>
   * gender of the passenger which is permitted to use the legitimation
   * </pre>
   *
   * <code>.OpenTicket.PassengerRecord.Gender gender = 4;</code>
   */
  int getGenderValue();
  /**
   * <pre>
   * gender of the passenger which is permitted to use the legitimation
   * </pre>
   *
   * <code>.OpenTicket.PassengerRecord.Gender gender = 4;</code>
   */
  PassengerRecord.Gender getGender();

  /**
   * <pre>
   * number of adult passengers
   * </pre>
   *
   * <code>uint32 numAdults = 5;</code>
   */
  int getNumAdults();

  /**
   * <pre>
   * number of children
   * </pre>
   *
   * <code>uint32 numChildren = 6;</code>
   */
  int getNumChildren();
}
