// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OpenTicket.proto

package org.openticket;

public interface ProductRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OpenTicket.ProductRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * human-readable product name (should be shortened in order to save memory!)
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * human-readable product name (should be shortened in order to save memory!)
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * human-readable info text (should be shortened in order to save memory!)
   * </pre>
   *
   * <code>string infoText = 2;</code>
   */
  java.lang.String getInfoText();
  /**
   * <pre>
   * human-readable info text (should be shortened in order to save memory!)
   * </pre>
   *
   * <code>string infoText = 2;</code>
   */
  com.google.protobuf.ByteString
      getInfoTextBytes();

  /**
   * <pre>
   * service class the ticket is valid for
   * </pre>
   *
   * <code>uint32 serviceClass = 3;</code>
   */
  int getServiceClass();
}
