// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OpenTicket.proto

package org.openticket;

public interface StopListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OpenTicket.StopList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * start stop ID
   * </pre>
   *
   * <code>uint32 startStopId = 1;</code>
   */
  int getStartStopId();

  /**
   * <pre>
   * all stop IDs which can be reached by the legitimation
   * </pre>
   *
   * <code>repeated uint32 containingStopIds = 2;</code>
   */
  java.util.List<java.lang.Integer> getContainingStopIdsList();
  /**
   * <pre>
   * all stop IDs which can be reached by the legitimation
   * </pre>
   *
   * <code>repeated uint32 containingStopIds = 2;</code>
   */
  int getContainingStopIdsCount();
  /**
   * <pre>
   * all stop IDs which can be reached by the legitimation
   * </pre>
   *
   * <code>repeated uint32 containingStopIds = 2;</code>
   */
  int getContainingStopIds(int index);
}
